---
- name: Test File
  hosts: all
 
  tasks:
  
  - name: make file
    copy: 
      content: "Test CentOS file from Ansible"
      dest: /tmp/test-centos.file
      force: false
      group: root
      mode: 0555
      owner: root
