---
- name: Test File
  hosts: "{{ ansible_fqdn }}"
 
  tasks:
  
  - name: make file
    copy: 
      content: "Hi from {{ ansible_fqdn }}\n"
      dest: /tmp/test-centos.file
      force: false
      group: root
      mode: 0555
      owner: root
