---
- name: Test File
  hosts: all
 
  tasks:
  
  - name: make file
    copy: 
      content: "Hi from {{ lookup('env', 'ansible_fqdn') }}"
      dest: /tmp/test-centos.file
      force: false
      group: root
      mode: 0555
      owner: root
